2025-06-11 22:04:35,871 INFO    MainThread:96036 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-06-11 22:04:35,871 INFO    MainThread:96036 [wandb_setup.py:_flush():81] Configure stats pid to 96036
2025-06-11 22:04:35,871 INFO    MainThread:96036 [wandb_setup.py:_flush():81] Loading settings from /root/.config/wandb/settings
2025-06-11 22:04:35,871 INFO    MainThread:96036 [wandb_setup.py:_flush():81] Loading settings from /data/LimitNet/newPlan/wandb/settings
2025-06-11 22:04:35,871 INFO    MainThread:96036 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-11 22:04:35,871 INFO    MainThread:96036 [wandb_init.py:setup_run_log_directory():703] Logging user logs to ./checkpoints_detection/wandb/offline-run-20250611_220435-yz1b5i7r/logs/debug.log
2025-06-11 22:04:35,871 INFO    MainThread:96036 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to ./checkpoints_detection/wandb/offline-run-20250611_220435-yz1b5i7r/logs/debug-internal.log
2025-06-11 22:04:35,872 INFO    MainThread:96036 [wandb_init.py:init():831] calling init triggers
2025-06-11 22:04:35,872 INFO    MainThread:96036 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-06-11 22:04:35,872 INFO    MainThread:96036 [wandb_init.py:init():872] starting backend
2025-06-11 22:04:36,145 INFO    MainThread:96036 [wandb_init.py:init():875] sending inform_init request
2025-06-11 22:04:36,179 INFO    MainThread:96036 [wandb_init.py:init():883] backend started and connected
2025-06-11 22:04:36,184 INFO    MainThread:96036 [wandb_init.py:init():956] updated telemetry
2025-06-11 22:04:36,251 INFO    MainThread:96036 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-06-11 22:04:36,302 INFO    MainThread:96036 [wandb_init.py:init():1032] starting run threads in backend
2025-06-11 22:04:36,399 INFO    MainThread:96036 [wandb_run.py:_console_start():2453] atexit reg
2025-06-11 22:04:36,399 INFO    MainThread:96036 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-06-11 22:04:36,400 INFO    MainThread:96036 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-06-11 22:04:36,400 INFO    MainThread:96036 [wandb_run.py:_redirect():2393] Redirects installed.
2025-06-11 22:04:36,401 INFO    MainThread:96036 [wandb_init.py:init():1078] run started, returning control to user process
2025-06-11 22:04:36,407 INFO    MainThread:96036 [wandb_run.py:_config_callback():1358] config_cb None None {'model_type': 'cifar', 'detector_config': {'model_path': 'yolo11n.pt', 'conf_threshold': 0.25, 'iou_threshold': 0.45, 'device': 'cuda'}}
2025-06-11 22:05:41,392 INFO    MsgRouterThr:96036 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
2025-06-11 22:05:41,591 ERROR   MainThread:96036 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2374, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-11 22:05:41,593 ERROR   MainThread:96036 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2374, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/data/LimitNet/newPlan/myenv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
